/**
 * Fillable-PDF readback + review model.
 *
 * Reads AcroForm field values from a customer-returned PDF (generated by Quill's
 * Fillable export) and maps them onto the app's data model so the returned
 * values can be reviewed and selectively applied. Deliberately tolerant:
 *  - not every PDF has every field;
 *  - legacy/alternate field names are aliased;
 *  - a PDF with no recognisable fields returns `recognized: false`.
 *
 * The review model is a proper change-review:
 *  - it distinguishes a field that is MISSING from the PDF from one that is
 *    present but returned BLANK (a deliberate clear);
 *  - dates are normalised with a forgiving parser (ordinals, month names,
 *    several numeric orders) and flagged when ambiguous or unparseable;
 *  - nothing is applied without an explicit action, and each `apply()` is pure.
 */
import {
  PDFDocument,
  PDFTextField,
  PDFDropdown,
  PDFOptionList,
  PDFRadioGroup,
  PDFCheckBox,
} from 'pdf-lib'
import type { OrderFormData, PaymentMethod } from '@/state/types'
import { PAYMENT_METHODS } from '@/state/types'
import { formatCurrency, formatDate, parseNumber } from '@/lib/format'

export type ReviewSection =
  | 'comments'
  | 'commercial'
  | 'customer'
  | 'soldTo'
  | 'billing'
  | 'signature'

export const SECTION_LABELS: Record<ReviewSection, string> = {
  comments: 'Customer Comments',
  commercial: 'Commercial Changes',
  customer: 'Customer Information',
  soldTo: 'Sold To',
  billing: 'Billing & Shipping',
  signature: 'Execution / Signature',
}

/** Priority order in the drawer — comments first, signature last. */
const SECTION_ORDER: ReviewSection[] = [
  'comments',
  'commercial',
  'customer',
  'soldTo',
  'billing',
  'signature',
]

export type ReviewStatus =
  | 'new' // current blank, returned non-empty
  | 'changed' // current non-empty, returned different non-empty
  | 'cleared' // current non-empty, returned blank (field present in PDF)
  | 'same' // current and returned match
  | 'empty' // both blank
  | 'not-returned' // field absent from the PDF
  | 'needs-correction' // returned value present but couldn't be parsed/normalised

export type ParseStatus = 'parsed' | 'ambiguous' | 'failed' | 'notApplicable'

type FieldKind = 'text' | 'date' | 'comment'
type Validation = { ok: true; value: string } | { ok: false; note: string }

type ReviewFieldDef = {
  id: string
  section: ReviewSection
  label: string
  kind: FieldKind
  /** Primary field name first, then legacy/alternate aliases. */
  pdfNames: string[]
  /** Comparable/stored form of the current value (ISO for dates, raw otherwise). */
  currentRaw: (d: OrderFormData) => string
  /** Human display of the current value. */
  currentDisplay: (d: OrderFormData) => string
  /** Apply a stored value ('' clears the field). Pure. */
  apply: (d: OrderFormData, storedRaw: string) => OrderFormData
  /** Optional normalisation/validation for non-date text values. */
  validate?: (returnedTrim: string) => Validation
}

// ---- Smart date parsing -----------------------------------------------------

const MONTHS: Record<string, number> = {
  jan: 1, january: 1, feb: 2, february: 2, mar: 3, march: 3, apr: 4, april: 4,
  may: 5, jun: 6, june: 6, jul: 7, july: 7, aug: 8, august: 8, sep: 9, sept: 9,
  september: 9, oct: 10, october: 10, nov: 11, november: 11, dec: 12, december: 12,
}

function pad(n: number): string {
  return String(n).padStart(2, '0')
}

/** Build a validated ISO date, or null if the components don't form a real date. */
function mkIso(y: number, mo: number, day: number): string | null {
  if (mo < 1 || mo > 12 || day < 1 || day > 31) return null
  const dt = new Date(y, mo - 1, day)
  if (dt.getFullYear() !== y || dt.getMonth() !== mo - 1 || dt.getDate() !== day) return null
  return `${y}-${pad(mo)}-${pad(day)}`
}

export type DateParse =
  | { status: 'parsed'; iso: string }
  | { status: 'ambiguous'; iso: string; altIso: string }
  | { status: 'failed' }

/**
 * Parse a human-entered date into ISO. Handles ordinals ("30th"), month names
 * (case-insensitive, full or abbreviated), and several numeric orders. A purely
 * numeric date where both leading parts are ≤ 12 (e.g. 07/08/2026) is reported
 * `ambiguous` with both readings (primary = day/month, matching the field
 * tooltip's dd/mm/yyyy hint).
 */
export function parseSmartDate(input: string): DateParse {
  const t = (input ?? '')
    .replace(/(\d{1,2})(st|nd|rd|th)\b/gi, '$1') // strip ordinals
    .replace(/\s+/g, ' ')
    .trim()
  if (!t) return { status: 'failed' }

  // ISO
  let m = /^(\d{4})-(\d{1,2})-(\d{1,2})$/.exec(t)
  if (m) {
    const iso = mkIso(+m[1], +m[2], +m[3])
    return iso ? { status: 'parsed', iso } : { status: 'failed' }
  }
  // D Month YYYY  ("30 July 2026", "30-Jul-2026")
  m = /^(\d{1,2})[ \-]([A-Za-z]+)[ \-,]*(\d{4})$/.exec(t)
  if (m) {
    const mo = MONTHS[m[2].toLowerCase()]
    const iso = mo ? mkIso(+m[3], mo, +m[1]) : null
    if (iso) return { status: 'parsed', iso }
  }
  // Month D, YYYY  ("July 30, 2026", "Jul 30 2026")
  m = /^([A-Za-z]+)[ ]+(\d{1,2})[ ,]+(\d{4})$/.exec(t)
  if (m) {
    const mo = MONTHS[m[1].toLowerCase()]
    const iso = mo ? mkIso(+m[3], mo, +m[2]) : null
    if (iso) return { status: 'parsed', iso }
  }
  // Numeric A/B/YYYY (/, - or .)
  m = /^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})$/.exec(t)
  if (m) {
    const a = +m[1]
    const b = +m[2]
    const y = +m[3]
    if (a > 12 && b <= 12) {
      const iso = mkIso(y, b, a) // dd/mm
      if (iso) return { status: 'parsed', iso }
    } else if (b > 12 && a <= 12) {
      const iso = mkIso(y, a, b) // mm/dd
      if (iso) return { status: 'parsed', iso }
    } else if (a <= 12 && b <= 12) {
      const dayFirst = mkIso(y, b, a) // dd/mm (primary — matches tooltip)
      const monthFirst = mkIso(y, a, b) // mm/dd
      if (dayFirst && monthFirst) return { status: 'ambiguous', iso: dayFirst, altIso: monthFirst }
      if (dayFirst) return { status: 'parsed', iso: dayFirst }
      if (monthFirst) return { status: 'parsed', iso: monthFirst }
    }
    return { status: 'failed' }
  }
  // Last resort: the JS Date parser (covers a few more spellings).
  const dt = new Date(t)
  if (!Number.isNaN(dt.getTime())) {
    return { status: 'parsed', iso: `${dt.getFullYear()}-${pad(dt.getMonth() + 1)}-${pad(dt.getDate())}` }
  }
  return { status: 'failed' }
}

// ---- Field descriptors (the mapping layer) ----------------------------------

const setCustomer = (d: OrderFormData, patch: Partial<OrderFormData['signature']['customer']>): OrderFormData => ({
  ...d,
  signature: { ...d.signature, customer: { ...d.signature.customer, ...patch } },
})

export const REVIEW_FIELDS: ReviewFieldDef[] = [
  // ---- Customer Comments (most important review signal) --------------------
  {
    id: 'subscription.comments',
    section: 'comments',
    label: 'Customer comment on Subscription Details',
    kind: 'comment',
    pdfNames: ['subscription.comments', 'paymentTerms.comments'], // legacy alias
    currentRaw: (d) => d.subscriptionComments,
    currentDisplay: (d) => d.subscriptionComments,
    apply: (d, v) => ({ ...d, subscriptionComments: v }),
  },
  {
    id: 'terms.comments',
    section: 'comments',
    label: 'Customer comment on Terms & Conditions',
    kind: 'comment',
    pdfNames: ['terms.comments'],
    currentRaw: (d) => d.termsComments,
    currentDisplay: (d) => d.termsComments,
    apply: (d, v) => ({ ...d, termsComments: v }),
  },
  // ---- Commercial ----------------------------------------------------------
  {
    id: 'subscription.startDate',
    section: 'commercial',
    label: 'Subscription Start Date',
    kind: 'date',
    pdfNames: ['subscription.startDate'],
    currentRaw: (d) => d.subscription.startDate,
    currentDisplay: (d) => formatDate(d.subscription.startDate),
    apply: (d, v) => ({ ...d, subscription: { ...d.subscription, startDate: v } }),
  },
  {
    id: 'subscription.paymentMethod',
    section: 'commercial',
    label: 'Payment Method',
    kind: 'text',
    pdfNames: ['subscription.paymentMethod'],
    currentRaw: (d) => d.subscription.paymentMethod,
    currentDisplay: (d) => d.subscription.paymentMethod,
    apply: (d, v) => ({ ...d, subscription: { ...d.subscription, paymentMethod: v as PaymentMethod } }),
    validate: (v) =>
      (PAYMENT_METHODS as string[]).includes(v)
        ? { ok: true, value: v }
        : { ok: false, note: 'Not one of the standard payment methods.' },
  },
  {
    id: 'purchaseOrder.required',
    section: 'commercial',
    label: 'PO Required',
    kind: 'text',
    pdfNames: ['po.required', 'purchaseOrder.required'],
    currentRaw: (d) => d.purchaseOrder.required,
    currentDisplay: (d) => d.purchaseOrder.required,
    apply: (d, v) => ({ ...d, purchaseOrder: { ...d.purchaseOrder, required: (v === 'Yes' ? 'Yes' : 'No') } }),
    validate: (v) => {
      const l = v.toLowerCase()
      if (l === 'yes') return { ok: true, value: 'Yes' }
      if (l === 'no') return { ok: true, value: 'No' }
      return { ok: false, note: 'Expected Yes or No.' }
    },
  },
  {
    id: 'purchaseOrder.number',
    section: 'commercial',
    label: 'PO Number',
    kind: 'text',
    pdfNames: ['po.number', 'purchaseOrder.number'],
    currentRaw: (d) => d.purchaseOrder.number,
    currentDisplay: (d) => d.purchaseOrder.number,
    apply: (d, v) => ({ ...d, purchaseOrder: { ...d.purchaseOrder, number: v } }),
  },
  {
    id: 'purchaseOrder.amount',
    section: 'commercial',
    label: 'PO Amount',
    kind: 'text',
    pdfNames: ['po.amount', 'purchaseOrder.amount'],
    currentRaw: (d) => d.purchaseOrder.amount,
    currentDisplay: (d) =>
      d.purchaseOrder.amount ? formatCurrency(parseNumber(d.purchaseOrder.amount), d.currency) : '',
    apply: (d, v) => ({ ...d, purchaseOrder: { ...d.purchaseOrder, amount: v } }),
    validate: (v) => {
      const n = parseNumber(v.replace(/[^0-9.]/g, ''))
      return n > 0 ? { ok: true, value: String(n) } : { ok: false, note: 'Couldn’t read this as an amount.' }
    },
  },
  // ---- Customer / Sold To / Billing ----------------------------------------
  {
    id: 'customer.legalName',
    section: 'customer',
    label: 'Customer Legal Name',
    kind: 'text',
    pdfNames: ['customer.legalName'],
    currentRaw: (d) => d.customer.legalName,
    currentDisplay: (d) => d.customer.legalName,
    apply: (d, v) => ({ ...d, customer: { ...d.customer, legalName: v } }),
  },
  {
    id: 'soldTo.name',
    section: 'soldTo',
    label: 'Name',
    kind: 'text',
    pdfNames: ['soldTo.name'],
    currentRaw: (d) => d.soldTo.name,
    currentDisplay: (d) => d.soldTo.name,
    apply: (d, v) => ({ ...d, soldTo: { ...d.soldTo, name: v } }),
  },
  {
    id: 'soldTo.email',
    section: 'soldTo',
    label: 'Email',
    kind: 'text',
    pdfNames: ['soldTo.email'],
    currentRaw: (d) => d.soldTo.email,
    currentDisplay: (d) => d.soldTo.email,
    apply: (d, v) => ({ ...d, soldTo: { ...d.soldTo, email: v } }),
  },
  {
    id: 'billing.name',
    section: 'billing',
    label: 'Bill To Name',
    kind: 'text',
    pdfNames: ['billing.name'],
    currentRaw: (d) => d.billing.billTo.name,
    currentDisplay: (d) => d.billing.billTo.name,
    apply: (d, v) => ({ ...d, billing: { ...d.billing, billTo: { ...d.billing.billTo, name: v } } }),
  },
  {
    id: 'billing.address',
    section: 'billing',
    label: 'Bill To Address',
    kind: 'text',
    pdfNames: ['billing.address'],
    currentRaw: (d) => d.billing.billTo.address,
    currentDisplay: (d) => d.billing.billTo.address,
    apply: (d, v) => ({ ...d, billing: { ...d.billing, billTo: { ...d.billing.billTo, address: v } } }),
  },
  {
    id: 'shipping.name',
    section: 'billing',
    label: 'Ship To Name',
    kind: 'text',
    pdfNames: ['shipping.name'],
    currentRaw: (d) => (d.billing.sameAsBillTo ? d.billing.billTo.name : d.billing.shipTo.name),
    currentDisplay: (d) => (d.billing.sameAsBillTo ? d.billing.billTo.name : d.billing.shipTo.name),
    apply: (d, v) => ({
      ...d,
      billing: { ...d.billing, sameAsBillTo: false, shipTo: { ...d.billing.shipTo, name: v } },
    }),
  },
  {
    id: 'shipping.address',
    section: 'billing',
    label: 'Ship To Address',
    kind: 'text',
    pdfNames: ['shipping.address'],
    currentRaw: (d) => (d.billing.sameAsBillTo ? d.billing.billTo.address : d.billing.shipTo.address),
    currentDisplay: (d) => (d.billing.sameAsBillTo ? d.billing.billTo.address : d.billing.shipTo.address),
    apply: (d, v) => ({
      ...d,
      billing: { ...d.billing, sameAsBillTo: false, shipTo: { ...d.billing.shipTo, address: v } },
    }),
  },
  // ---- Execution / Signature -----------------------------------------------
  {
    id: 'customer.name',
    section: 'signature',
    label: 'Customer Name',
    kind: 'text',
    pdfNames: ['customer.name'],
    currentRaw: (d) => d.signature.customer.name,
    currentDisplay: (d) => d.signature.customer.name,
    apply: (d, v) => setCustomer(d, { name: v }),
  },
  {
    id: 'customer.designation',
    section: 'signature',
    label: 'Customer Designation',
    kind: 'text',
    pdfNames: ['customer.designation'],
    currentRaw: (d) => d.signature.customer.designation,
    currentDisplay: (d) => d.signature.customer.designation,
    apply: (d, v) => setCustomer(d, { designation: v }),
  },
  {
    id: 'customer.signDate',
    section: 'signature',
    label: 'Customer Sign Date',
    kind: 'date',
    pdfNames: ['customer.signDate', 'customer.date'],
    currentRaw: (d) => d.signature.customer.date,
    currentDisplay: (d) => formatDate(d.signature.customer.date),
    apply: (d, v) => setCustomer(d, { date: v }),
  },
  {
    id: 'customer.signature',
    section: 'signature',
    label: 'Customer Signature (typed name)',
    kind: 'text',
    pdfNames: ['customer.signature'],
    currentRaw: (d) => d.signature.customer.signatureName,
    currentDisplay: (d) => d.signature.customer.signatureName,
    apply: (d, v) => setCustomer(d, { type: 'typed', signatureName: v }),
  },
]

const KNOWN_PDF_NAMES = new Set(REVIEW_FIELDS.flatMap((f) => f.pdfNames))

// ---- Reading the PDF --------------------------------------------------------

export type ReadResult =
  | { ok: true; values: Record<string, string>; recognized: boolean }
  | { ok: false; error: string }

/** Extract every AcroForm field value from the uploaded PDF as a name→string map. */
export async function readPdfFields(bytes: Uint8Array): Promise<ReadResult> {
  let doc: PDFDocument
  try {
    doc = await PDFDocument.load(bytes, { ignoreEncryption: true })
  } catch {
    return { ok: false, error: 'This file couldn’t be opened as a PDF.' }
  }
  const values: Record<string, string> = {}
  try {
    const form = doc.getForm()
    for (const f of form.getFields()) {
      const name = f.getName()
      let v = ''
      if (f instanceof PDFTextField) v = f.getText() ?? ''
      else if (f instanceof PDFDropdown) v = f.getSelected()[0] ?? ''
      else if (f instanceof PDFOptionList) v = f.getSelected()[0] ?? ''
      else if (f instanceof PDFRadioGroup) v = f.getSelected() ?? ''
      else if (f instanceof PDFCheckBox) v = f.isChecked() ? 'Yes' : 'No'
      values[name] = v
    }
  } catch {
    /* no AcroForm — recognized:false below */
  }
  const recognized = Object.keys(values).some((n) => KNOWN_PDF_NAMES.has(n))
  return { ok: true, values, recognized }
}

// ---- Review model -----------------------------------------------------------

export type ReviewItem = {
  id: string
  section: ReviewSection
  label: string
  kind: FieldKind
  fieldFound: boolean
  returnedValue: string | null
  currentDisplay: string
  returnedDisplay: string
  /** Stored form to apply (ISO for dates; '' for a clear). null when unparseable. */
  normalizedValue: string | null
  /** Human display of the normalised value (dates only). */
  interpretedDisplay?: string
  /** For ambiguous dates: the alternative reading, for display. */
  ambiguousAltDisplay?: string
  parseStatus: ParseStatus
  status: ReviewStatus
  /** Included in "Apply all safe changes". */
  safe: boolean
  /** Whether Apply/Clear can proceed with the returned value as-is. */
  appliable: boolean
  note?: string
}

export type ReviewGroup = { section: ReviewSection; label: string; items: ReviewItem[] }

const norm = (s: string) => s.trim().replace(/\s+/g, ' ').toLowerCase()

/** Build the grouped, current-vs-returned review model from extracted values. */
export function buildReviewModel(data: OrderFormData, values: Record<string, string>): ReviewGroup[] {
  const bySection = new Map<ReviewSection, ReviewItem[]>()

  for (const def of REVIEW_FIELDS) {
    const presentName = def.pdfNames.find((n) => n in values)
    if (!presentName) continue // field absent from PDF → 'not-returned', hidden

    const returnedRaw = values[presentName] ?? ''
    const returnedTrim = returnedRaw.trim()
    const currentRaw = def.currentRaw(data)
    const currentBlank = !currentRaw.trim()
    const currentDisplay = def.currentDisplay(data)

    let parseStatus: ParseStatus = 'notApplicable'
    let normalizedValue: string | null = null
    let interpretedDisplay: string | undefined
    let ambiguousAltDisplay: string | undefined
    let note: string | undefined
    let status: ReviewStatus
    let appliable = false

    if (returnedTrim === '') {
      // Present but blank → a deliberate clear (or nothing, if current is blank).
      normalizedValue = ''
      status = currentBlank ? 'empty' : 'cleared'
      appliable = status === 'cleared'
    } else if (def.kind === 'date') {
      const r = parseSmartDate(returnedTrim)
      parseStatus = r.status
      if (r.status === 'failed') {
        status = 'needs-correction'
        note = 'Couldn’t read this as a date — enter the corrected date.'
      } else {
        normalizedValue = r.iso
        interpretedDisplay = formatDate(r.iso)
        if (r.status === 'ambiguous') {
          ambiguousAltDisplay = formatDate(r.altIso)
          note = 'Ambiguous date — please confirm before applying.'
        }
        status = norm(r.iso) === norm(currentRaw) ? 'same' : currentBlank ? 'new' : 'changed'
        appliable = true
      }
    } else {
      // text / comment
      const v = def.validate ? def.validate(returnedTrim) : ({ ok: true, value: returnedTrim } as Validation)
      if (v.ok) {
        normalizedValue = v.value
        appliable = true
      } else {
        note = v.note
      }
      const cmp = normalizedValue ?? returnedTrim
      status = norm(cmp) === norm(currentRaw) ? 'same' : currentBlank ? 'new' : 'changed'
    }

    const safe = status === 'new' && appliable && parseStatus !== 'ambiguous'

    const item: ReviewItem = {
      id: def.id,
      section: def.section,
      label: def.label,
      kind: def.kind,
      fieldFound: true,
      returnedValue: returnedRaw,
      currentDisplay,
      returnedDisplay: returnedTrim,
      normalizedValue,
      interpretedDisplay,
      ambiguousAltDisplay,
      parseStatus,
      status,
      safe,
      appliable,
      note,
    }
    const arr = bySection.get(def.section) ?? []
    arr.push(item)
    bySection.set(def.section, arr)
  }

  return SECTION_ORDER.filter((s) => bySection.has(s)).map((s) => ({
    section: s,
    label: SECTION_LABELS[s],
    items: bySection.get(s)!,
  }))
}

/**
 * Apply a review item's value to the data (pure). `override` supplies a
 * user-corrected/confirmed value (e.g. a manually entered date, or an ISO
 * chosen for an ambiguous date). For a cleared field the stored value is ''.
 */
export function applyReviewItem(
  data: OrderFormData,
  item: ReviewItem,
  override?: string,
): OrderFormData {
  const def = REVIEW_FIELDS.find((f) => f.id === item.id)
  if (!def) return data
  let value: string | null
  if (override !== undefined) value = override
  else if (item.status === 'cleared') value = ''
  else value = item.normalizedValue
  if (value === null) return data // needs-correction with no override — nothing to apply
  return def.apply(data, value)
}

export type ReviewSummary = {
  comments: number
  newCount: number
  changed: number
  cleared: number
  needsCorrection: number
  unchanged: number
}

/** Counts for the drawer's import summary. */
export function summarizeReview(groups: ReviewGroup[]): ReviewSummary {
  const items = groups.flatMap((g) => g.items)
  return {
    comments: items.filter((i) => i.kind === 'comment' && !!i.returnedDisplay).length,
    newCount: items.filter((i) => i.status === 'new').length,
    changed: items.filter((i) => i.status === 'changed').length,
    cleared: items.filter((i) => i.status === 'cleared').length,
    needsCorrection: items.filter((i) => i.status === 'needs-correction').length,
    unchanged: items.filter((i) => i.status === 'same' || i.status === 'empty').length,
  }
}
