/**
 * Fillable-PDF readback + review model.
 *
 * Reads AcroForm field values from a customer-returned PDF (generated by Quill's
 * Fillable export) and maps them onto the app's data model so the returned
 * values can be reviewed and selectively applied. Deliberately tolerant:
 *  - not every PDF has every field;
 *  - legacy/alternate field names are aliased;
 *  - a PDF with no recognisable fields returns `recognized: false` (the caller
 *    shows a friendly message) rather than throwing.
 *
 * This module never mutates the app — it produces a review model. Applying is
 * done field-by-field via the pure `apply()` functions on each descriptor, so
 * a non-empty existing value is only ever overwritten on an explicit Apply.
 */
import {
  PDFDocument,
  PDFTextField,
  PDFDropdown,
  PDFOptionList,
  PDFRadioGroup,
  PDFCheckBox,
} from 'pdf-lib'
import type { OrderFormData, PaymentMethod } from '@/state/types'
import { PAYMENT_METHODS } from '@/state/types'
import { formatCurrency, formatDate, parseNumber } from '@/lib/format'

export type ReviewSection =
  | 'customer'
  | 'soldTo'
  | 'billing'
  | 'subscription'
  | 'subscriptionReview'
  | 'termsReview'
  | 'signature'
  | 'purchaseOrder'

export const SECTION_LABELS: Record<ReviewSection, string> = {
  customer: 'Customer Information',
  soldTo: 'Sold To',
  billing: 'Billing & Shipping',
  subscription: 'Subscription Details',
  subscriptionReview: 'Subscription Details Review',
  termsReview: 'Terms & Conditions Review',
  signature: 'Execution / Signature',
  purchaseOrder: 'Purchase Order',
}

export type ReviewStatus = 'new' | 'changed' | 'same' | 'empty'

type Normalized = { ok: true; stored: string } | { ok: false; note: string }

type ReviewFieldDef = {
  id: string
  section: ReviewSection
  label: string
  kind: 'value' | 'comment'
  /** Primary field name first, then legacy/alternate aliases. */
  pdfNames: string[]
  current: (d: OrderFormData) => string
  /** Convert a raw returned string into the value we store (or explain why not). */
  normalize: (returned: string, d: OrderFormData) => Normalized
  apply: (d: OrderFormData, stored: string) => OrderFormData
}

// ---- Loose date parsing (fillable prefills a formatted/typed date) ----------

function pad(n: number): string {
  return String(n).padStart(2, '0')
}

/** Parse ISO, "Aug 01, 2026", or dd/mm/yyyy (the field tooltip's format) → ISO, else null. */
export function parseLooseDate(input: string): string | null {
  const t = (input ?? '').trim()
  if (!t) return null
  // dd/mm/yyyy | dd-mm-yyyy | dd.mm.yyyy (tooltip says dd/mm/yyyy)
  const dmy = /^(\d{1,2})[/.\- ](\d{1,2})[/.\- ](\d{4})$/.exec(t)
  if (dmy) {
    const dd = +dmy[1]
    const mm = +dmy[2]
    const yyyy = +dmy[3]
    if (mm >= 1 && mm <= 12 && dd >= 1 && dd <= 31) {
      const iso = `${yyyy}-${pad(mm)}-${pad(dd)}`
      if (!Number.isNaN(new Date(iso).getTime())) return iso
    }
  }
  if (/^\d{4}-\d{2}-\d{2}$/.test(t)) {
    if (!Number.isNaN(new Date(t).getTime())) return t
  }
  const d = new Date(t)
  if (!Number.isNaN(d.getTime())) return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
  return null
}

// ---- Field descriptors (the mapping layer) ----------------------------------

const identity = (returned: string): Normalized => ({ ok: true, stored: returned.trim() })

export const REVIEW_FIELDS: ReviewFieldDef[] = [
  {
    id: 'customer.legalName',
    section: 'customer',
    label: 'Customer Legal Name',
    kind: 'value',
    pdfNames: ['customer.legalName'],
    current: (d) => d.customer.legalName,
    normalize: identity,
    apply: (d, stored) => ({ ...d, customer: { ...d.customer, legalName: stored } }),
  },
  {
    id: 'soldTo.name',
    section: 'soldTo',
    label: 'Name',
    kind: 'value',
    pdfNames: ['soldTo.name'],
    current: (d) => d.soldTo.name,
    normalize: identity,
    apply: (d, stored) => ({ ...d, soldTo: { ...d.soldTo, name: stored } }),
  },
  {
    id: 'soldTo.email',
    section: 'soldTo',
    label: 'Email',
    kind: 'value',
    pdfNames: ['soldTo.email'],
    current: (d) => d.soldTo.email,
    normalize: identity,
    apply: (d, stored) => ({ ...d, soldTo: { ...d.soldTo, email: stored } }),
  },
  {
    id: 'billing.name',
    section: 'billing',
    label: 'Bill To Name',
    kind: 'value',
    pdfNames: ['billing.name'],
    current: (d) => d.billing.billTo.name,
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      billing: { ...d.billing, billTo: { ...d.billing.billTo, name: stored } },
    }),
  },
  {
    id: 'billing.address',
    section: 'billing',
    label: 'Bill To Address',
    kind: 'value',
    pdfNames: ['billing.address'],
    current: (d) => d.billing.billTo.address,
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      billing: { ...d.billing, billTo: { ...d.billing.billTo, address: stored } },
    }),
  },
  {
    id: 'shipping.name',
    section: 'billing',
    label: 'Ship To Name',
    kind: 'value',
    pdfNames: ['shipping.name'],
    current: (d) => (d.billing.sameAsBillTo ? d.billing.billTo.name : d.billing.shipTo.name),
    normalize: identity,
    // A returned ship-to means a distinct shipping address, so unlink from Bill To.
    apply: (d, stored) => ({
      ...d,
      billing: { ...d.billing, sameAsBillTo: false, shipTo: { ...d.billing.shipTo, name: stored } },
    }),
  },
  {
    id: 'shipping.address',
    section: 'billing',
    label: 'Ship To Address',
    kind: 'value',
    pdfNames: ['shipping.address'],
    current: (d) => (d.billing.sameAsBillTo ? d.billing.billTo.address : d.billing.shipTo.address),
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      billing: {
        ...d.billing,
        sameAsBillTo: false,
        shipTo: { ...d.billing.shipTo, address: stored },
      },
    }),
  },
  {
    id: 'subscription.startDate',
    section: 'subscription',
    label: 'Start Date',
    kind: 'value',
    pdfNames: ['subscription.startDate'],
    current: (d) => formatDate(d.subscription.startDate),
    normalize: (returned) => {
      const iso = parseLooseDate(returned)
      return iso
        ? { ok: true, stored: iso }
        : { ok: false, note: 'Couldn’t read this as a date — enter it manually.' }
    },
    apply: (d, stored) => ({ ...d, subscription: { ...d.subscription, startDate: stored } }),
  },
  {
    id: 'subscription.paymentMethod',
    section: 'subscription',
    label: 'Payment Method',
    kind: 'value',
    pdfNames: ['subscription.paymentMethod'],
    current: (d) => d.subscription.paymentMethod,
    normalize: (returned) => {
      const v = returned.trim()
      return (PAYMENT_METHODS as string[]).includes(v)
        ? { ok: true, stored: v }
        : { ok: false, note: 'Not one of the standard payment methods.' }
    },
    apply: (d, stored) => ({
      ...d,
      subscription: { ...d.subscription, paymentMethod: stored as PaymentMethod },
    }),
  },
  {
    id: 'subscription.comments',
    section: 'subscriptionReview',
    label: 'Customer comment on Subscription Details',
    kind: 'comment',
    // New name first; legacy paymentTerms.comments still imports into the same field.
    pdfNames: ['subscription.comments', 'paymentTerms.comments'],
    current: (d) => d.subscriptionComments,
    normalize: identity,
    apply: (d, stored) => ({ ...d, subscriptionComments: stored }),
  },
  {
    id: 'terms.comments',
    section: 'termsReview',
    label: 'Customer comment on Terms & Conditions',
    kind: 'comment',
    pdfNames: ['terms.comments'],
    current: (d) => d.termsComments,
    normalize: identity,
    apply: (d, stored) => ({ ...d, termsComments: stored }),
  },
  {
    id: 'customer.name',
    section: 'signature',
    label: 'Customer Name',
    kind: 'value',
    pdfNames: ['customer.name'],
    current: (d) => d.signature.customer.name,
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      signature: { ...d.signature, customer: { ...d.signature.customer, name: stored } },
    }),
  },
  {
    id: 'customer.designation',
    section: 'signature',
    label: 'Customer Designation',
    kind: 'value',
    pdfNames: ['customer.designation'],
    current: (d) => d.signature.customer.designation,
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      signature: { ...d.signature, customer: { ...d.signature.customer, designation: stored } },
    }),
  },
  {
    id: 'customer.signDate',
    section: 'signature',
    label: 'Customer Sign Date',
    kind: 'value',
    pdfNames: ['customer.signDate', 'customer.date'],
    current: (d) => formatDate(d.signature.customer.date),
    normalize: (returned) => {
      const iso = parseLooseDate(returned)
      return iso
        ? { ok: true, stored: iso }
        : { ok: false, note: 'Couldn’t read this as a date — enter it manually.' }
    },
    apply: (d, stored) => ({
      ...d,
      signature: { ...d.signature, customer: { ...d.signature.customer, date: stored } },
    }),
  },
  {
    id: 'customer.signature',
    section: 'signature',
    label: 'Customer Signature (typed name)',
    kind: 'value',
    pdfNames: ['customer.signature'],
    current: (d) => d.signature.customer.signatureName,
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      signature: {
        ...d.signature,
        customer: { ...d.signature.customer, type: 'typed', signatureName: stored },
      },
    }),
  },
  {
    id: 'purchaseOrder.required',
    section: 'purchaseOrder',
    label: 'PO Required',
    kind: 'value',
    pdfNames: ['po.required', 'purchaseOrder.required'],
    current: (d) => d.purchaseOrder.required,
    normalize: (returned) => {
      const v = returned.trim().toLowerCase()
      if (v === 'yes') return { ok: true, stored: 'Yes' }
      if (v === 'no') return { ok: true, stored: 'No' }
      return { ok: false, note: 'Expected Yes or No.' }
    },
    apply: (d, stored) => ({
      ...d,
      purchaseOrder: { ...d.purchaseOrder, required: stored as 'Yes' | 'No' },
    }),
  },
  {
    id: 'purchaseOrder.number',
    section: 'purchaseOrder',
    label: 'PO Number',
    kind: 'value',
    pdfNames: ['po.number', 'purchaseOrder.number'],
    current: (d) => d.purchaseOrder.number,
    normalize: identity,
    apply: (d, stored) => ({
      ...d,
      purchaseOrder: { ...d.purchaseOrder, number: stored },
    }),
  },
  {
    id: 'purchaseOrder.amount',
    section: 'purchaseOrder',
    label: 'PO Amount',
    kind: 'value',
    pdfNames: ['po.amount', 'purchaseOrder.amount'],
    current: (d) =>
      d.purchaseOrder.amount ? formatCurrency(parseNumber(d.purchaseOrder.amount), d.currency) : '',
    normalize: (returned) => {
      const digits = returned.replace(/[^0-9.]/g, '')
      const n = parseNumber(digits)
      return digits && n > 0
        ? { ok: true, stored: String(n) }
        : { ok: false, note: 'Couldn’t read this as an amount.' }
    },
    apply: (d, stored) => ({ ...d, purchaseOrder: { ...d.purchaseOrder, amount: stored } }),
  },
]

const KNOWN_PDF_NAMES = new Set(REVIEW_FIELDS.flatMap((f) => f.pdfNames))

// ---- Reading the PDF --------------------------------------------------------

export type ReadResult =
  | { ok: true; values: Record<string, string>; recognized: boolean }
  | { ok: false; error: string }

/** Extract every AcroForm field value from the uploaded PDF as a name→string map. */
export async function readPdfFields(bytes: Uint8Array): Promise<ReadResult> {
  let doc: PDFDocument
  try {
    doc = await PDFDocument.load(bytes, { ignoreEncryption: true })
  } catch {
    return { ok: false, error: 'This file couldn’t be opened as a PDF.' }
  }
  const values: Record<string, string> = {}
  try {
    const form = doc.getForm()
    for (const f of form.getFields()) {
      const name = f.getName()
      let v = ''
      if (f instanceof PDFTextField) v = f.getText() ?? ''
      else if (f instanceof PDFDropdown) v = f.getSelected()[0] ?? ''
      else if (f instanceof PDFOptionList) v = f.getSelected()[0] ?? ''
      else if (f instanceof PDFRadioGroup) v = f.getSelected() ?? ''
      else if (f instanceof PDFCheckBox) v = f.isChecked() ? 'Yes' : 'No'
      values[name] = v
    }
  } catch {
    // A PDF with no AcroForm at all → no values (recognized:false downstream).
  }
  const recognized = Object.keys(values).some((n) => KNOWN_PDF_NAMES.has(n))
  return { ok: true, values, recognized }
}

// ---- Review model -----------------------------------------------------------

export type ReviewItem = {
  id: string
  section: ReviewSection
  label: string
  kind: 'value' | 'comment'
  currentDisplay: string
  returnedDisplay: string
  status: ReviewStatus
  /** New + parseable → auto-appliable in "Apply all safe changes". */
  safe: boolean
  /** Whether Apply is possible (present, non-empty, and normalises cleanly). */
  appliable: boolean
  note?: string
  /** Normalised value to store when applied (present only when appliable). */
  stored?: string
}

export type ReviewGroup = { section: ReviewSection; label: string; items: ReviewItem[] }

const norm = (s: string) => s.trim().replace(/\s+/g, ' ').toLowerCase()

/** Build the grouped, current-vs-returned review model from extracted values. */
export function buildReviewModel(
  data: OrderFormData,
  values: Record<string, string>,
): ReviewGroup[] {
  const bySection = new Map<ReviewSection, ReviewItem[]>()

  for (const def of REVIEW_FIELDS) {
    const presentName = def.pdfNames.find((n) => n in values)
    if (!presentName) continue // field wasn't in this PDF — skip entirely
    const returnedRaw = (values[presentName] ?? '').trim()
    const currentDisplay = def.current(data)

    let status: ReviewStatus
    let appliable = false
    let stored: string | undefined
    let note: string | undefined

    if (!returnedRaw) {
      status = 'empty'
    } else {
      const n = def.normalize(returnedRaw, data)
      if (n.ok) {
        stored = n.stored
        appliable = true
      } else {
        note = n.note
      }
      if (norm(returnedRaw) === norm(currentDisplay)) status = 'same'
      else if (!currentDisplay.trim()) status = 'new'
      else status = 'changed'
    }

    const item: ReviewItem = {
      id: def.id,
      section: def.section,
      label: def.label,
      kind: def.kind,
      currentDisplay,
      returnedDisplay: returnedRaw,
      status,
      appliable,
      safe: status === 'new' && appliable,
      note,
      stored,
    }
    const arr = bySection.get(def.section) ?? []
    arr.push(item)
    bySection.set(def.section, arr)
  }

  const order: ReviewSection[] = [
    'customer',
    'soldTo',
    'billing',
    'subscription',
    'subscriptionReview',
    'termsReview',
    'signature',
    'purchaseOrder',
  ]
  return order
    .filter((s) => bySection.has(s))
    .map((s) => ({ section: s, label: SECTION_LABELS[s], items: bySection.get(s)! }))
}

/** Apply a single item's stored value to the data (pure). */
export function applyReviewItem(data: OrderFormData, item: ReviewItem): OrderFormData {
  if (!item.appliable || item.stored === undefined) return data
  const def = REVIEW_FIELDS.find((f) => f.id === item.id)
  return def ? def.apply(data, item.stored) : data
}
